=== AntonSias/Lenguaje_de_Marcas_A02/BibliotecaXSDSergi.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Biblioteca">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded">
   <!-- LIBRO-->   
  <xs:element name="libro">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="titulo" type="xs:string"/>
        <xs:element name="capitulo" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="titulo" type="xs:string"/>
              <xs:element name="contenido">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="informacion" type="xs:string"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="numero_paginas" type="xs:integer" use="required"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="sinopsis" type="xs:string"/>
        <xs:element name="indice" type="xs:string"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:string" use="required"/>
      <xs:attribute name="tipo_clase" default="novela">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="novela"/>
            <xs:enumeration value="infantil"/>
            <xs:enumeration value="didactico"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="numero_paginas" type="xs:integer" use="required"/>
    </xs:complexType>
  </xs:element>

        <!-- Revistas -->
      <xs:element name="revista">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="titulo" type="xs:string"/>
        <xs:element name="numero_revista" type="xs:string"/>
        <xs:element name="indice_contenido" type="xs:string"/>
        <xs:element name="seccion" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="contenidorevista">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:anyURI">
                      <xs:attribute name="enlace_informacion" type="xs:anyURI" use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="numero_paginas" type="xs:integer"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="id" type="xs:string" use="required"/>
      <xs:attribute name="tipo" type="xs:string" use="required"/>
      <xs:attribute name="numero_paginas" type="xs:integer" use="required"/>
    </xs:complexType>
  </xs:element>

    <!--Periodico-->
  <xs:element name="periodico">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="seccionperiodico" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="articulo" maxOccurs="10">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="autor" type="xs:string" use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="tipo" use="required">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:enumeration value="nacional" />
                  <xs:enumeration value="internacional" />
                  <xs:enumeration value="deportes" />
                  <xs:enumeration value="opinion" />
                  <xs:enumeration value="economia" />
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
        <xs:element name="indiceperiodico" type="xs:string" />
        <xs:element name="contenidoperiodico" type="xs:string" />
      </xs:sequence>
      <xs:attribute name="tipo_clase" use="optional" default="internacional">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="nacional" />
            <xs:enumeration value="internacional" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="fecha_publicacion" type="xs:date"/>
    </xs:complexType>
  </xs:element>
            </xs:choice>
        </xs:complexType>
</xs:element>
</xs:schema>

=== AntonSias/Lenguaje_de_Marcas_A02/BibliotecaXML_XSDSergi.xml
<?xml version="1.0" encoding="UTF-8"?>
<Biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:noNamespaceSchemaLocation= "BibliotecaXSDSergi.xsd">
<!-- LIBROS-->
  <libro id="L001" tipo_clase="novela" numero_paginas="200">
    <titulo>Historia de los griegos</titulo>
    <capitulo numero_paginas="25">
      <titulo>Capitulo 1º Minos</titulo>
      <contenido informacion="Personajes principales">Entramos en los inicios de la grecia antigua...</contenido>
    </capitulo>
    <capitulo numero_paginas="50">
      <titulo>Capítulo 2 Schliemann</titulo>
      <contenido informacion="El primer día en la Universidad">Falta poco para los hablar de los filosofos ..</contenido>
    </capitulo>
    <sinopsis>La contribución de Grecia a la civilizacion occidental es vasta y facinante.</sinopsis>
    <indice>Prólogo, Capítulo 1, Capítulo 2, Capítulo 3, ...</indice>
  </libro>
  <!-- REVISTA-->
  <revista id="R001" tipo="otros" numero_paginas="100">
    <titulo>Cahiers du cinema</titulo>
    <numero_revista>123</numero_revista>
    <indice_contenido>Entrevistas, análisis, y crítica </indice_contenido>
     <seccion numero_paginas="10">
    <contenidorevista enlace_informacion="https://www.caimanediciones.es/entrevista-alberto-gastesi-version-ampliada-de-caiman-cdc-no-177/">Entrevista a Alberto Gastesi</contenidorevista>
  </seccion>
  <seccion numero_paginas="20">
      <contenidorevista enlace_informacion="https://www.caimanediciones.es/my-sunny-maad-michaela-pavlatova/">Crítica My Sunny Maad d</contenidorevista>
  </seccion>
  </revista>
  <!-- PERIODICO-->
   <periodico tipo_clase="nacional" fecha_publicacion="2023-05-10">
  <seccionperiodico tipo="nacional">
    <articulo autor="Zairzalejos">Una cura para el amor</articulo>
    <articulo autor="Carlos Ansinas">David Suarez contra el humor</articulo>
    <articulo autor="Jorge Javier Vázquez">Isabel Preysley después de muchos años revela sus técnicas filipinas</articulo>
  </seccionperiodico>
  <seccionperiodico tipo="opinion">
    <articulo autor="Beyonce Suárez">¿Por qué tantos adolescentes están solteros?</articulo>
    <articulo autor="Josep Piquet Shakiro">Las vacas amenazan la humanidad</articulo>
  </seccionperiodico>
  <indiceperiodico>Portada, Sociedad, Opinión</indiceperiodico>
  <contenidoperiodico>Sumamos información y entretenimiento.</contenidoperiodico>
</periodico>
</Biblioteca>
