=== AntonSias/Lenguaje_de_Marcas_A02/BibliotecaDTDSergi.dtd
<!ELEMENT Biblioteca (libro | revista | periodico)*>
<!-- LIBRO-->
<!ELEMENT libro (titulo, capitulo+, sinopsis, indice)>
<!ATTLIST libro id CDATA #REQUIRED>
<!ATTLIST libro tipo_clase CDATA #IMPLIED>
<!ATTLIST libro numero_paginas CDATA #IMPLIED>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT capitulo (titulo, contenido)>
<!ATTLIST capitulo numero_paginas CDATA #IMPLIED>
<!ELEMENT contenido (#PCDATA)>
<!ATTLIST contenido informacion CDATA #IMPLIED>
<!ELEMENT sinopsis (#PCDATA)>
<!ELEMENT indice (#PCDATA)>
<!-- REVISTA-->
<!ELEMENT revista (titulo, numero_revista, indice_contenido, seccionrevista+)>
<!ATTLIST revista id ID #REQUIRED>
<!ATTLIST revista tipo CDATA #IMPLIED>
<!ATTLIST revista numero_paginasrevista CDATA #IMPLIED>
<!ELEMENT numero_revista (#PCDATA)>
<!ELEMENT indice_contenido (#PCDATA)>
<!ELEMENT seccionrevista (contenidorevista)>
<!ATTLIST seccionrevista numero_paginas CDATA #IMPLIED>
<!ATTLIST contenidorevista enlace_informacion CDATA #IMPLIED>
<!ATTLIST seccionrevista tipo CDATA #IMPLIED>
<!ELEMENT contenidorevista (#PCDATA)>
<!-- PERIÃ“DICO-->
<!ELEMENT periodico (seccionperiodico+, indiceperiodico, contenidoperiodico)>
<!ATTLIST periodico tipo_clase CDATA #IMPLIED>
<!ATTLIST periodico fecha_publicacion CDATA #REQUIRED>
<!ELEMENT seccionperiodico (articulo)* >
<!ATTLIST seccionperiodico tipo ID #REQUIRED>
<!ELEMENT articulo (#PCDATA )>
<!ATTLIST articulo autor CDATA #IMPLIED>
<!ATTLIST articulo tipo CDATA #IMPLIED>
<!ELEMENT indiceperiodico (#PCDATA)>
<!ELEMENT contenidoperiodico (#PCDATA)>

=== AntonSias/Lenguaje_de_Marcas_A02/BIbliotecaXML_DTD.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Biblioteca SYSTEM "BibliotecaDTDSergi.dtd">

<Biblioteca>
  <libro id="L001" tipo_clase="novela" numero_paginas="200">
    <titulo>Historia de los griegos</titulo>
    <capitulo>
      <titulo>Capitulo 1º Minos</titulo>
      <contenido informacion="Personajes principales">Entramos en los inicios de la grecia antigua...</contenido>
    </capitulo>
    <capitulo>
      <titulo>Capítulo 2 Schliemann</titulo>
      <contenido informacion="El primer día en la Universidad">Falta poco para los hablar de los filosofos ..</contenido>
    </capitulo>
    <sinopsis>La contribución de Grecia a la civilizacion occidental es vasta y facinante.</sinopsis>
    <indice>Prólogo, Capítulo 1, Capítulo 2, Capítulo 3, ...</indice>
  </libro>
  <revista id="R001" tipo="otras" numero_paginasrevista="100">
    <titulo>Cahiers du cinema</titulo>
    <numero_revista>123</numero_revista>   
    <indice_contenido>Entrevistas, análisis, y crítica </indice_contenido>
    <seccionrevista numero_paginas="20" enlace_informacion="https://www.caimanediciones.es/entrevista-alberto-gastesi-version-ampliada-de-caiman-cdc-no-177/">
      <contenidorevista>Entrevista a Alberto Gastesi</contenidorevista>
    </seccionrevista>
    <seccionrevista numero_paginas="30" enlace_informacion="https://www.caimanediciones.es/my-sunny-maad-michaela-pavlatova/">
      <contenidorevista>Crítica My Sunny Maad d</contenidorevista>
    </seccionrevista>
  </revista>
   <periodico tipo_clase="nacional">
    <seccionperiodico autor="Zairzalejos" tipo="sociedad" >
      <articulo>Una cura para el amor </articulo>
      <articulo>David Suarez contra el humor</articulo>
      <articulo>Isabel Preysle nos revela lo que es la practica del carrete</articulo>
     
    </seccionperiodico>
    <seccionperiodico autor="Josefina Molona " tipo="opinion">
      <articulo>¿Por qué tantos adolescentes están solteros?</articulo>
      <articulo> Las vacas amenazan la humanidad</articulo>
    </seccionperiodico>
    <indiceperiodico>Portada, Sociedad, Opinión</indiceperiodico>
    <contenidoperiodico>Sumamos informacion y entretenimiento.</contenidoperiodico>
  </periodico>
</Biblioteca>
