<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE biblioteca [
<!ELEMENT biblioteca (libro |  revista |  periodico)*>
<!ELEMENT libro (titulo, capitulo, indice, sipnosis)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT capitulo (titulo, contenido)>
<!ELEMENT contenido (#PCDATA)>
<!ELEMENT indice (#PCDATA)>
<!ELEMENT sipnosis (#PCDATA)>

<!ELEMENT revista (titulo, numero_revista, indice_de_contenido, seccion)>

<!ELEMENT numero_de_revista (#PCDATA)>
<!ELEMENT indice_de_contenido (#PCDATA)>
<!ELEMENT seccion (contenido)>



<!ELEMENT periodico (seccion, indice, contenido )>
<!ELEMENT articulo (#PCDATA)>



<!--Definimos
atributos-->
<!ATTLIST libro id ID #REQUIRED>
<!ATTLIST libro tipo_clase (novela | infantil | didáctico)  #REQUIRED>
<!ATTLIST libro numero_paginas CDATA >
<!ATTLIST capitulo numero_pagina CDATA #REQUIRED>
<!ATTLIST revista id ID #REQUIRED>
<!ATTLIST revista tipo_clase(informatica | corazon | coches | investigacion | otras) #REQUIRED>
<!ATTLIST seccion numero_paginas  >
<!ATTLIST contenido enlace_informacion CDATA #REQUIRED>
<!ATTLIST periodico id ID #REQUIRED>
<!ATTLIST periodico fecha_publicación CDATA #REQUIRED>
<!ATTLIST periodico tipo_clase(nacional | internacional) #REQUIRED>
<!ATTLIST contenido enlace_informacion CDATA #REQUIRED>
]>

<biblioteca>

    <libro id="L2564" tipo_clase="didactico" numero_paginas="361">
        <titulo>Historia de los griegos</titulo>
        <capitulo numero_paginas="10">
            <titulo> Homero </titulo>
            <contenido informacion="wikipedia"> Resumen del capítulo</contenido>
        </capitulo>

        <indice> Estructura Texto</indice>
        <sipnosis>Historia de los griegos constituye una obra inteligente y rigurosa ...</sipnosis>
    </libro>

<revista id="R5288" tipo_clase="otras" numero_paginas="105">
        <titulo>Cahiers du cinema</titulo>
        <numero_revista>125</numero_revista>
        <indice_de_contenido></indice_de_contenido>
        <seccion numero_paginas="5">
            <contenido enlace_informacion="www.cahiersducinema.com">
                www.cahiersducinema.com/entrevistas/almodovar</contenido>
        </seccion>
    </revista>

    <periodico id="P6923" fecha_publicacion="8-5-2023" tipo_clase="Nacional">

        <seccion tipo_sección="Economía">
            <articulos autor="Julio López"> España en la encrucijada del pleno empleo</articulos>
        </seccion>
        <indice></indice>
        <contenido enlace_informacion="www.elconfidencial.com">
            www.elconfidencial.con/economía/españa_en_la_encrucijada </contenido>
    </periodico>


</biblioteca>   
